import type { LucideIcon } from "lucide-react";
import {
  Bell,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  CheckCircle2,
  Code2,
  Cloud,
  FileText,
  Flag,
  FolderOpen,
  Database,
  Globe,
  Heart,
  Home,
  Image as ImageIcon,
  Layers,
  LayoutDashboard,
  Lightbulb,
  Link2,
  Lock,
  Rocket,
  Search,
  Shield,
  Mail,
  MapPin,
  Pencil,
  MessageSquare,
  Music,
  Palette,
  Phone,
  Settings,
  ShoppingCart,
  Star,
  StickyNote,
  Target,
  Terminal,
  Download,
  Upload,
  User,
  Video,
  Sparkles,
  Zap,
} from "lucide-react";

export type FolderLucidePreset = { id: string; Icon: LucideIcon; label: string };

export const FOLDER_LUCIDE_PRESETS: FolderLucidePreset[] = [
  { id: "CheckCircle2", Icon: CheckCircle2, label: "완료" },
  { id: "Mail", Icon: Mail, label: "이메일" },
  { id: "Link2", Icon: Link2, label: "링크" },
  { id: "StickyNote", Icon: StickyNote, label: "메모" },
  { id: "Calendar", Icon: Calendar, label: "캘린더" },
  { id: "FolderOpen", Icon: FolderOpen, label: "폴더" },
  { id: "Briefcase", Icon: Briefcase, label: "업무" },
  { id: "LayoutDashboard", Icon: LayoutDashboard, label: "보드" },
  { id: "Star", Icon: Star, label: "중요" },
  { id: "Heart", Icon: Heart, label: "관심" },
  { id: "Home", Icon: Home, label: "홈" },
  { id: "User", Icon: User, label: "사용자" },
  { id: "Bell", Icon: Bell, label: "알림" },
  { id: "ImageIcon", Icon: ImageIcon, label: "이미지" },
  { id: "FileText", Icon: FileText, label: "문서" },
  { id: "Zap", Icon: Zap, label: "빠름" },
  { id: "Target", Icon: Target, label: "목표" },
  { id: "Code2", Icon: Code2, label: "코드" },
  { id: "Palette", Icon: Palette, label: "디자인" },
  { id: "Layers", Icon: Layers, label: "레이어" },
  { id: "Flag", Icon: Flag, label: "깃발" },
  { id: "Bookmark", Icon: Bookmark, label: "북마크" },
  { id: "MessageSquare", Icon: MessageSquare, label: "채팅" },
  { id: "Phone", Icon: Phone, label: "전화" },
  { id: "MapPin", Icon: MapPin, label: "위치" },
  { id: "ShoppingCart", Icon: ShoppingCart, label: "쇼핑" },
  { id: "Globe", Icon: Globe, label: "웹" },
  { id: "Camera", Icon: Camera, label: "카메라" },
  { id: "Video", Icon: Video, label: "영상" },
  { id: "Music", Icon: Music, label: "음악" },
  { id: "Lightbulb", Icon: Lightbulb, label: "아이디어" },
  { id: "Search", Icon: Search, label: "검색" },
  { id: "Download", Icon: Download, label: "다운로드" },
  { id: "Upload", Icon: Upload, label: "업로드" },
  { id: "Pencil", Icon: Pencil, label: "편집" },
  { id: "Sparkles", Icon: Sparkles, label: "스파클" },
  { id: "Shield", Icon: Shield, label: "보안" },
  { id: "Settings", Icon: Settings, label: "설정" },
  { id: "Terminal", Icon: Terminal, label: "터미널" },
  { id: "Database", Icon: Database, label: "데이터" },
  { id: "Cloud", Icon: Cloud, label: "클라우드" },
  { id: "Rocket", Icon: Rocket, label: "런치" },
  { id: "Lock", Icon: Lock, label: "잠금" },
];

const byId = new Map(FOLDER_LUCIDE_PRESETS.map((p) => [p.id, p.Icon]));

export function resolveFolderLucideIcon(id: string | null | undefined): LucideIcon {
  if (!id) return FolderOpen;
  return byId.get(id) ?? FolderOpen;
}
